# Generated by Django 3.2.9 on 2021-11-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=16)),
                ('course_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_first_name', models.CharField(max_length=32)),
                ('instructor_last_name', models.CharField(max_length=32)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('instructor_dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=32)),
                ('student_last_name', models.CharField(max_length=32)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=32)),
                ('student_address', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('term_season', models.CharField(choices=[('SPRING', 'Spring'), ('FALL', 'Fall')], max_length=32)),
                ('term_year', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.instructor')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.studyterm')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.student')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.studyterm')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisapp.department'),
        ),
    ]
