# Generated by Django 3.2.9 on 2021-11-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.TextField(),
        ),
    ]
